const fs = require('fs');
let code = '';
code += 'def by_hour(rows):\n';
code += '    m = {}\n';
code += '    for r in rows:\n';
code += '        h = r.get("hour")\n';
code += '        if h is None: continue\n';
code += '        if h not in m:\n';
code += '            m[h] = {"count": 0, "reach": 0, "likes": 0, "comments": 0, "shares": 0, "_ers": []}\n';
code += '        m[h]["count"] += 1\n';
code += '        m[h]["reach"] += r.get("reach") or 0\n';
code += '        m[h]["likes"] += r.get("likes") or 0\n';
code += '        m[h]["comments"] += r.get("comments") or 0\n';
code += '        m[h]["shares"] += r.get("shares") or 0\n';
code += '        if r["er"] is not None and r["reach"] > 0:\n';
code += '            m[h]["_ers"].append(r["er"])\n';
code += '    out = []\n';
code += '    for k, v in m.items():\n';
code += '        avg_er = sum(v["_ers"]) / len(v["_ers"]) if v["_ers"] else None\n';
code += '        out.append({"hour": int(k), "count": v["count"], "reach": v["reach"], "likes": v["likes"], "comments": v["comments"], "shares": v["shares"], "avgER": avg_er})\n';
code += '    return sorted(out, key=lambda x: x["hour"])\n\n';
code += 'def by_day(rows):\n';
code += '    m = {}\n';
code += '    for r in rows:\n';
code += '        d = r.get("date")\n';
code += '        if not d: continue\n';
code += '        if d not in m:\n';
code += '            m[d] = {"count": 0, "reach": 0, "likes": 0, "comments": 0, "shares": 0, "_ers": []}\n';
code += '        m[d]["count"] += 1\n';
code += '        m[d]["reach"] += r.get("reach") or 0\n';
code += '        m[d]["likes"] += r.get("likes") or 0\n';
code += '        m[d]["comments"] += r.get("comments") or 0\n';
code += '        m[d]["shares"] += r.get("shares") or 0\n';
code += '        if r["er"] is not None and r["reach"] > 0:\n';
code += '            m[d]["_ers"].append(r["er"])\n';
code += '    out = []\n';
code += '    for k, v in m.items():\n';
code += '        avg_er = sum(v["_ers"]) / len(v["_ers"]) if v["_ers"] else None\n';
code += '        out.append({"date": k, "count": v["count"], "reach": v["reach"], "likes": v["likes"], "comments": v["comments"], "shares": v["shares"], "avgER": avg_er})\n';
code += '    return sorted(out, key=lambda x: x["date"])\n\n';
code += 'fb_stats = stats(fb_rows)\n';
code += 'ig_stats = stats(ig_rows)\n';
code += 'fb_by_type = by_type(fb_rows, "type")\n';
code += 'ig_by_type = by_type(ig_rows, "type")\n';
code += 'fb_by_hour = by_hour(fb_rows)\n';
code += 'ig_by_hour = by_hour(ig_rows)\n';
code += 'fb_by_day = by_day(fb_rows)\n';
code += 'ig_by_day = by_day(ig_rows)\n\n';
code += 'yesterday_path = ANALYTICS_DIR / ("report_" + YESTERDAY + ".json")\n';
code += 'yesterday = None\n';
code += 'if yesterday_path.exists():\n';
code += '    try: yesterday = json.loads(yesterday_path.read_text(encoding="utf-8"))\n';
code += '    except: yesterday = None\n\n';
code += 'fb_top = sorted([r for r in fb_rows if r["reach"] > 0], key=lambda x: (x["er"] or 0), reverse=True)[:10]\n';
code += 'ig_top = sorted([r for r in ig_rows if r["reach"] > 0], key=lambda x: (x["er"] or 0), reverse=True)[:10]\n\n';
code += 'recs = []\n\n';
code += 'if fb_by_hour:\n';
code += '    best_fb = sorted(fb_by_hour, key=lambda h: (h["avgER"] or 0), reverse=True)[:3]\n';
code += '    recs.append({"priority": "CRITICAL", "area": "HORARIOS FACEBOOK", "finding": "Top 3 horas FB por engagement rate", "data": [str(h["hour"]) + "h WAT (" + ("%.2f" % (h["avgER"] or 0)) + "% ER, " + str(h["count"]) + " posts)" for h in best_fb], "action": "Concentrar cron jobs nestas horas"})\n\n';
code += 'if ig_by_hour:\n';
code += '    best_ig = sorted(ig_by_hour, key=lambda h: (h["avgER"] or 0), reverse=True)[:3]\n';
code += '    recs.append({"priority": "CRITICAL", "area": "HORARIOS INSTAGRAM", "finding": "Top 3 horas IG por engagement rate", "data": [str(h["hour"]) + "h WAT (" + ("%.2f" % (h["avgER"] or 0)) + "% ER, " + str(h["count"]) + " posts)" for h in best_ig], "action": "Publicar nos horarios de pico"})\n\n';
code += 'if fb_by_type:\n';
code += '    recs.append({"priority": "HIGH", "area": "FORMATOS FACEBOOK", "finding": "Performance por tipo de post", "data": [t["type"] + ": " + str(t["count"]) + " posts, ER " + ("%.2f" % (t["avgER"] or 0)) + "%, reach " + str(t["reach"]) for t in fb_by_type], "action": "Aumentar frequencia do tipo com melhor ER"})\n\n';
code += 'if ig_by_type:\n';
code += '    recs.append({"priority": "HIGH", "area": "FORMATOS INSTAGRAM", "finding": "Performance por media type", "data": [t["type"] + ": " + str(t["count"]) + " posts, ER " + ("%.2f" % (t["avgER"] or 0)) + "%, reach " + str(t["reach"]) for t in ig_by_type], "action": "Aumentar frequencia do tipo com melhor ER (CAROUSEL/VIDEO/IMAGE)"})\n\n';
code += 'if fb_stats["avgER"] is not None and fb_stats["avgER"] < 1:\n';
code += '    recs.append({"priority": "CRITICAL", "area": "CTA FRACO FACEBOOK", "finding": "ER medio FB = " + ("%.3f" % fb_stats["avgER"]) + "% (benchmark: >1%)", "data": [], "action": "CTAs diretos: Encomenda agora, Chama no DM, Link na bio"})\n';
code += 'if ig_stats["avgER"] is not None and ig_stats["avgER"] < 1:\n';
code += '    recs.append({"priority": "CRITICAL", "area": "CTA FRACO INSTAGRAM", "finding": "ER medio IG = " + ("%.3f" % ig_stats["avgER"]) + "% (benchmark: >1%)", "data": [], "action": "Stories + Reels tem ER 3-5x maior. Investir."})\n\n';
code += 'recs.append({"priority": "HIGH", "area": "VOLUME", "finding": "FB " + str(len(fb_rows)) + " posts, IG " + str(len(ig_rows)) + " media nos ultimos ~25 dias", "data": ["FB: " + ("%.1f" % (len(fb_rows)/25)) + " posts/dia", "IG: " + ("%.1f" % (len(ig_rows)/25)) + " media/dia"], "action": "Angola mercado pequeno: 1-2 posts/dia FB, 1-2 IG + Stories + Reels 2-3x semana"})\n\n';
code += 'fb_promo = [r for r in fb_rows if "Promo" in (r.get("msg") or "")]\n';
code += 'if fb_promo:\n';
code += '    recs.append({"priority": "MEDIUM", "area": "CONTEUDO REPETITIVO", "finding": str(len(fb_promo)) + " de " + str(len(fb_rows)) + " posts FB sao template Promocoes do dia", "data": [], "action": "Variacao: unboxings, depoimentos, before/after, dicas de uso"})\n\n';
code += 'ig_reels = [r for r in ig_rows if r.get("type") == "VIDEO"]\n';
code += 'if len(ig_reels) < 5:\n';
code += '    recs.append({"priority": "HIGH", "area": "POUCO REELS/STORIES", "finding": "Apenas " + str(len(ig_reels)) + " Reels/videos nos ultimos 100 media IG", "data": [], "action": "Reels tem alcance organico 3-5x maior. Minimo 2-3 Reels/semana."})\n\n';
code += 'report = {"generated_at": datetime.now(timezone.utc).isoformat(), "date": TODAY, "page": {"fb_id": FB_PAGE_ID, "ig": ig_acct}, "summary": {"fb": fb_stats, "ig": ig_stats}, "by_type": {"fb": fb_by_type, "ig": ig_by_type}, "by_hour": {"fb": fb_by_hour, "ig": ig_by_hour}, "by_day": {"fb": fb_by_day, "ig": ig_by_day}, "top_posts": {"fb": fb_top, "ig": ig_top}, "comparison_with_yesterday": yesterday, "recommendations": recs}\n';
code += 'report_file = ANALYTICS_DIR / ("report_" + TODAY + ".json")\n';
code += 'report_file.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")\n\n';
code += 'print()\n';
code += 'print("=" * 60)\n';
code += 'print("FINAL REPORT")\n';
code += 'print("=" * 60)\n';
code += 'print("Saved:", report_file)\n';
code += 'print()\n';
code += 'print("--- FB SUMMARY ---")\n';
code += 'print(json.dumps(fb_stats, indent=2, ensure_ascii=False))\n';
code += 'print()\n';
code += 'print("--- IG SUMMARY ---")\n';
code += '
